// <auto-generated />
using EcoEnergyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoEnergyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241122012607_EnergyMigration")]
    partial class EnergyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoEnergyAPI.Models.ContaLuzModel", b =>
                {
                    b.Property<int>("IdContaLuz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContaLuz"));

                    b.Property<string>("ClasseConsumo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<float>("DiasNoMes")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Impostos")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<float>("TarifaKWh")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("ValorConta")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("IdContaLuz");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("CONTA_LUZ");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.DispositivoModel", b =>
                {
                    b.Property<int>("IdDispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDispositivo"));

                    b.Property<float>("ConsumoWatts")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<string>("EstadoDispositivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeDispositivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoDispositivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdDispositivo");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("DISPOSITIVO");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.TarefaModel", b =>
                {
                    b.Property<int>("IdTarefa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarefa"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdTarefa");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("TAREFA");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.UsuarioModel", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.ContaLuzModel", b =>
                {
                    b.HasOne("EcoEnergyAPI.Models.UsuarioModel", "Usuario")
                        .WithMany("ContasLuz")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.DispositivoModel", b =>
                {
                    b.HasOne("EcoEnergyAPI.Models.UsuarioModel", "Usuario")
                        .WithMany("Dispositivos")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.TarefaModel", b =>
                {
                    b.HasOne("EcoEnergyAPI.Models.UsuarioModel", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoEnergyAPI.Models.UsuarioModel", b =>
                {
                    b.Navigation("ContasLuz");

                    b.Navigation("Dispositivos");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
